// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
var list_services_default = defineTool({
  name: "list_services",
  title: "Listar servicios",
  description: "Lista el cat\xE1logo p\xFAblico de servicios y categor\xEDas activas de Asesores Migratorios.",
  inputSchema: {
    category_slug: z.string().trim().optional().describe("Filtrar por slug de categor\xEDa (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_slug }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("services").select("id, title, slug, description, category_id, service_categories!inner(name, slug)").eq("is_active", true);
    if (category_slug) query = query.eq("service_categories.slug", category_slug);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-ds160.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_ds160_default = defineTool2({
  name: "list_my_ds160_applications",
  title: "Mis solicitudes DS-160",
  description: "Lista las solicitudes DS-160 del usuario autenticado (respeta permisos y RLS).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("ds160_applications").select(
      "id, full_name, email, purpose_of_trip, embassy, status, current_step, created_at, submitted_at"
    ).is("deleted_at", null).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ds160.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_ds160_default = defineTool3({
  name: "get_ds160_application",
  title: "Ver solicitud DS-160",
  description: "Devuelve una solicitud DS-160 por id. Sujeta a RLS: solo el due\xF1o, secretar\xEDa con permiso activo o admin pueden verla.",
  inputSchema: {
    id: z2.string().uuid().describe("UUID de la solicitud DS-160.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("ds160_applications").select("*").eq("id", id).is("deleted_at", null).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No encontrada o sin acceso." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/tools/submit-review.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var submit_review_default = defineTool4({
  name: "submit_review",
  title: "Enviar rese\xF1a",
  description: "Env\xEDa una rese\xF1a del cliente para su aprobaci\xF3n por un administrador. Requiere sesi\xF3n.",
  inputSchema: {
    client_name: z3.string().trim().min(1).max(100),
    rating: z3.number().int().min(1).max(5),
    comment: z3.string().trim().min(1).max(1e3)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_name, rating, comment }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("reviews").insert({
      client_name,
      rating,
      comment,
      status: "pending"
    }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Rese\xF1a enviada (id ${data?.id}). Queda pendiente de aprobaci\xF3n por un administrador.`
        }
      ],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fngefvyaqllxpsqopplt";
var mcp_default = defineMcp({
  name: "asesores-migratorios-mcp",
  title: "Asesores Migratorios",
  version: "0.1.0",
  instructions: "Herramientas de Asesores Migratorios. Consulta el cat\xE1logo p\xFAblico de servicios, y con la sesi\xF3n del usuario, revisa tus solicitudes DS-160 y env\xEDa rese\xF1as para aprobaci\xF3n.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, list_my_ds160_default, get_ds160_default, submit_review_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
